#############################################################################
# Makefile for building QKantenEdit
# Generated by tmake at 21:37, 1998/07/05
#     Project: QKantenEdit 
#    Template: app
#    von Andre Betz
#############################################################################

QTDIR   =       /usr/lib/qt
CC	=	g++
CFLAGS	=	-Wall -W -O2 -fno-strength-reduce -g
INCPATH	=	-I$(QTDIR)/include 
LINK	=	g++
LFLAGS	=	
LIBS	=	-L$(QTDIR)/lib -lqt -L/usr/X11R6/lib -lX11  
MOC	=	/usr/bin/moc
HEADERS =	QNeuroGo.h GoBoard.h GoPlayer.h GoGroup.h myBackpropNet.h AsciiNeuroGo.h
SOURCES =	QNeuroGo.cpp GoBoard.cpp GoPlayer.cpp GoGroup.cpp myBackpropNet.cpp AsciiNeuroGo.cpp GoPlayer2.cpp GoPlayer3.cpp Paul.cpp GoStrato.cpp
OBJECTS =	QNeuroGo.o GoBoard.o GoPlayer.o GoGroup.o myBackpropNet.o AsciiNeuroGo.o GoPlayer2.o GoPlayer3.o Paul.o GoStrato.o
SRCMOC	=	QNeuroGo.moc
OBJMOC	=	
TARGET	=	QNeuroGo


.SUFFIXES: .cpp .cxx .cc .C .c

.cpp.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: $(TARGET)

$(TARGET): $(OBJECTS) $(OBJMOC)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(LIBS)

moc: $(SRCMOC)

clean:
	-rm -f $(OBJECTS) $(OBJMOC) $(SRCMOC) $(TARGET)
	-rm -f *~ core

####### Compile

QNeuroGo.o: QNeuroGo.cpp \
		QNeuroGo.moc \

QNeuroGo.moc: QNeuroGo.cpp
	$(MOC) QNeuroGo.cpp -o QNeuroGo.moc

GoBoard.o: GoBoard.cpp GoBoard.h

GoPlayer.o: GoPlayer.cpp GoPlayer.h backpropnet.h

GoGroup.o: GoGroup.cpp GoGroup.h

myBackpropNet.o: myBackpropNet.cpp myBackpropNet.cpp

AsciiNeuroGo.o: AsciiNeuroGo.cpp AsciiNeuroGo.h

GoPlayer2.o: GoPlayer2.cpp GoPlayer.h

GoPlayer3.o: GoPlayer3.cpp GoPlayer.h

GoStrato.o: GoStrato.cpp GoPlayer.h
